# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-18 06:03+0000\n"
"PO-Revision-Date: 2014-06-24 16:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/nova/language/"
"es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: nova/api/auth.py:73
msgid "ratelimit_v3 is removed from v3 api."
msgstr ""

#: nova/api/auth.py:160
msgid "Sourcing roles from deprecated X-Role HTTP header"
msgstr ""

#: nova/api/ec2/__init__.py:169
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and "
"will be locked out for %(lock_mins)d minutes."
msgstr ""

#: nova/api/ec2/cloud.py:1290
#: nova/api/openstack/compute/contrib/floating_ips.py:254
#, python-format
msgid "multiple fixed_ips exist, using the first: %s"
msgstr ""

#: nova/api/metadata/handler.py:119
msgid ""
"X-Instance-ID present in request headers. The 'service_metadata_proxy' "
"option must be enabled to process this header."
msgstr ""

#: nova/api/metadata/handler.py:189
#, python-format
msgid ""
"X-Instance-ID-Signature: %(signature)s does not match the expected value: "
"%(expected_signature)s for id: %(instance_id)s.  Request From: "
"%(remote_address)s"
msgstr ""

#: nova/api/metadata/handler.py:215
#, python-format
msgid ""
"Tenant_id %(tenant_id)s does not match tenant_id of instance %(instance_id)s."
msgstr ""

#: nova/api/metadata/vendordata_json.py:47
msgid "file does not exist"
msgstr ""

#: nova/api/metadata/vendordata_json.py:49
msgid "Unexpected IOError when reading"
msgstr ""

#: nova/api/metadata/vendordata_json.py:53
msgid "failed to load json"
msgstr ""

#: nova/api/openstack/__init__.py:235 nova/api/openstack/__init__.py:409
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:282
#: nova/api/openstack/compute/plugins/v3/servers.py:104
#, python-format
msgid "Not loading %s because it is in the blacklist"
msgstr ""

#: nova/api/openstack/__init__.py:287
#: nova/api/openstack/compute/plugins/v3/servers.py:109
#, python-format
msgid "Not loading %s because it is not in the whitelist"
msgstr ""

#: nova/api/openstack/__init__.py:307
#, python-format
msgid "Extensions in both blacklist and whitelist: %s"
msgstr ""

#: nova/api/openstack/common.py:456
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/extensions.py:279
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/compute/servers.py:82
msgid ""
"XML support has been deprecated and may be removed as early as the Juno "
"release."
msgstr ""

#: nova/api/openstack/compute/views/servers.py:197
msgid "Instance has had its instance_type removed from the DB"
msgstr ""

#: nova/compute/manager.py:2023
msgid "No more network or fixed IP to be allocated"
msgstr ""

#: nova/compute/manager.py:2263
#, python-format
msgid "Ignoring EndpointNotFound: %s"
msgstr ""

#: nova/compute/manager.py:2281
#, python-format
msgid "Failed to delete volume: %(volume_id)s due to %(exc)s"
msgstr ""

#: nova/compute/utils.py:204
#, python-format
msgid "Can't access image %(image_id)s: %(error)s"
msgstr ""

#: nova/compute/utils.py:328
#, python-format
msgid ""
"No host name specified for the notification of HostAPI.%s and it will be "
"ignored"
msgstr ""

#: nova/compute/utils.py:456
#, python-format
msgid ""
"Value of 0 or None specified for %s. This behaviour will change in meaning "
"in the K release, to mean 'call at the default rate' rather than 'do not "
"call'. To keep the 'do not call' behaviour, use a negative value."
msgstr ""

#: nova/compute/resources/__init__.py:31
#, python-format
msgid "Compute resource plugin %s was not loaded"
msgstr ""

#: nova/consoleauth/manager.py:84
#, python-format
msgid "Token: %(token)s failed to save into memcached."
msgstr ""

#: nova/consoleauth/manager.py:95
#, python-format
msgid "Instance: %(instance_uuid)s failed to save into memcached"
msgstr ""

#: nova/network/neutronv2/api.py:218
#, python-format
msgid "Neutron error: Port quota exceeded in tenant: %s"
msgstr ""

#: nova/network/neutronv2/api.py:223
#, python-format
msgid "Neutron error: No more fixed IPs in network: %s"
msgstr ""

#: nova/network/neutronv2/api.py:227
#, python-format
msgid ""
"Neutron error: MAC address %(mac)s is already in use on network %(network)s."
msgstr ""

#: nova/network/neutronv2/api.py:302
msgid "No network configured!"
msgstr ""

#: nova/network/neutronv2/api.py:497
#, python-format
msgid "Port %s does not exist"
msgstr ""

#: nova/network/neutronv2/api.py:1160
#, python-format
msgid ""
"Network %(id)s not matched with the tenants network! The ports tenant "
"%(tenant_id)s will be used."
msgstr ""

#: nova/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)s run outlasted interval by %(delay).2f sec"
msgstr ""

#: nova/openstack/common/network_utils.py:145
msgid "tcp_keepidle not available on your system"
msgstr ""

#: nova/openstack/common/network_utils.py:152
msgid "tcp_keepintvl not available on your system"
msgstr ""

#: nova/openstack/common/network_utils.py:159
msgid "tcp_keepknt not available on your system"
msgstr ""

#: nova/openstack/common/service.py:363
#, python-format
msgid "pid %d not in child list"
msgstr "El pid %d no está en la lista de hijos"

#: nova/openstack/common/db/sqlalchemy/session.py:506
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:559
msgid "Unable to detect effective SQL mode"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:567
#, python-format
msgid ""
"MySQL SQL mode is '%s', consider enabling TRADITIONAL or STRICT_ALL_TABLES"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:673
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr "La conexión SQL ha fallado. Quedan %s intentos."

#: nova/openstack/common/db/sqlalchemy/utils.py:96
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id no está en sort_keys; ¿es sort_keys exclusivo?"

#: nova/scheduler/filters/core_filter.py:51
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""
"VCPU no establecidas; suponiendo que la colección de CPU se ha interrumpido"

#: nova/scheduler/filters/core_filter.py:102
#, python-format
msgid "Could not decode cpu_allocation_ratio: '%s'"
msgstr "No se puede decodificar cpu_allocation_ratio: '%s'"

#: nova/scheduler/filters/ram_filter.py:95
#, python-format
msgid "Could not decode ram_allocation_ratio: '%s'"
msgstr "No se puede decodificar ram_allocation_ratio: '%s'"

#: nova/storage/linuxscsi.py:100
#, python-format
msgid "Multipath call failed exit (%(code)s)"
msgstr ""

#: nova/storage/linuxscsi.py:121
#, python-format
msgid "Couldn't find multipath device %s"
msgstr ""

#: nova/storage/linuxscsi.py:130
#, python-format
msgid "Skip faulty line \"%(dev_line)s\" of multipath device %(mdev)s"
msgstr ""

#: nova/virt/disk/api.py:366
#, python-format
msgid "Ignoring error injecting data into image %(image)s (%(e)s)"
msgstr ""

#: nova/virt/disk/api.py:456
#, python-format
msgid "Ignoring error injecting %(inject)s into image (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/api.py:44
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/libvirt/driver.py:376
#, python-format
msgid "Invalid cachemode %(cache_mode)s specified for disk type %(disk_type)s."
msgstr ""
"Modalidad de caché %(cache_mode)s no válida especificada para el tipo de "
"disco %(disk_type)s."

#: nova/virt/libvirt/driver.py:614
#, python-format
msgid ""
"The libvirt driver is not tested on %(type)s/%(arch)s by the OpenStack "
"project and thus its quality can not be ensured. For more information, see: "
"https://wiki.openstack.org/wiki/HypervisorSupportMatrix"
msgstr ""
"El controlador libvirt no ha sido probado en %(type)s/%(arch)s por el "
"projecto de OpenStack  por lo cual su calidad no puede ser asegurada. Para "
"mas información, ver: https://wiki.openstack.org/wiki/HypervisorSupportMatrix"

#: nova/virt/libvirt/driver.py:671
#, python-format
msgid "URI %(uri)s does not support events: %(error)s"
msgstr "URI %(uri)s no soporta eventos: %(error)s"

#: nova/virt/libvirt/driver.py:687
#, python-format
msgid "URI %(uri)s does not support connection events: %(error)s"
msgstr "URI %(uri)s no soporta eventos de conexión: %(error)s"

#: nova/virt/libvirt/driver.py:919
msgid "Cannot destroy instance, operation time out"
msgstr ""
"No se puede destruir intsancia, tiempo de espera agotado para la operación"

#: nova/virt/libvirt/driver.py:943
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1027
msgid "Instance may be still running, destroy it again."
msgstr "Puede que la instancia aún se esté ejecutando, vuelva a destruirla."

#: nova/virt/libvirt/driver.py:1080
#, python-format
msgid "Ignoring Volume Error on vol %(vol_id)s during delete %(exc)s"
msgstr ""
"Ignorando Error de volumen en volumen %(vol_id)s durante la remocion %(exc)s"

#: nova/virt/libvirt/driver.py:1130
#, python-format
msgid "Volume %(disk)s possibly unsafe to remove, please clean up manually"
msgstr ""
"El volumen %(disk)s es posiblemente inseguro para remover, por favor "
"límpialo manualmente"

#: nova/virt/libvirt/driver.py:1414 nova/virt/libvirt/driver.py:1422
msgid "During detach_volume, instance disappeared."
msgstr "Durante detach_volume, la instancia ha desaparecido."

#: nova/virt/libvirt/driver.py:1467
msgid "During detach_interface, instance disappeared."
msgstr "Durante detach_interface, la instancia ha desaparecido."

#: nova/virt/libvirt/driver.py:2136
msgid "Failed to soft reboot instance. Trying hard reboot."
msgstr ""
"Fallo al reiniciar la instancia de manera suave. Intentando reinicio duro."

#: nova/virt/libvirt/driver.py:2693
#, python-format
msgid "Image %s not found on disk storage. Continue without injecting data"
msgstr ""
"La imagen %s no se ha encontrado en el almacenamiento de disco. Continuando "
"sin inyectar datos."

#: nova/virt/libvirt/driver.py:2880
msgid "File injection into a boot from volume instance is not supported"
msgstr ""
"La inyección de archivo al arranque desde la instancia del volumen no está "
"soportado."

#: nova/virt/libvirt/driver.py:2955
msgid "Instance disappeared while detaching a PCI device from it."
msgstr ""
"La instancia ha desaparecido mientras se removía el dispositivo PCI de ella."

#: nova/virt/libvirt/driver.py:3010
#, python-format
msgid "Cannot update service status on host: %s,since it is not registered."
msgstr ""
"No se puede actualizar el estado del servicio en el anfitrión: %s, ya que el "
"mismo no está registrado."

#: nova/virt/libvirt/driver.py:3013
#, python-format
msgid ""
"Cannot update service status on host: %s,due to an unexpected exception."
msgstr ""
"No se puede atualizar el estado del servicio en el anfitrión: %s, debido a "
"una excepción inesperada."

#: nova/virt/libvirt/driver.py:3041
#, python-format
msgid "URI %(uri)s does not support full set of host capabilities: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3888
#, python-format
msgid "Timeout waiting for vif plugging callback for instance %(uuid)s"
msgstr ""
"Tiempo excedido para la llamada inversa de la conexión vif para la instancia "
"%(uuid)s"

#: nova/virt/libvirt/driver.py:3909
#, python-format
msgid "couldn't obtain the XML from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3966
msgid ""
"Cannot get the number of cpu, because this function is not implemented for "
"this platform. "
msgstr ""
"No se puede obtener el número de CPU porque esta función no está "
"implementada para esta plataforma. "

#: nova/virt/libvirt/driver.py:4028
#, python-format
msgid ""
"couldn't obtain the vpu count from domain id: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4059
#, python-format
msgid "couldn't obtain the memory from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4261
#, python-format
msgid "URI %(uri)s does not support listDevices: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4916
#, python-format
msgid "plug_vifs() failed %(cnt)d. Retry up to %(max_retry)d."
msgstr "plug_vifs() ha fallado %(cnt)d. Intentando hasta %(max_retry)d."

#: nova/virt/libvirt/driver.py:5126
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error "
"Code %(error_code)s] %(ex)s"
msgstr ""
"Error de libvirt al obtener la descripción de %(instance_name)s: [Código de "
"error %(error_code)s] %(ex)s"

#: nova/virt/libvirt/driver.py:5134
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but disk file was removed by concurrent operations such as "
"resize."
msgstr ""
"La tarea periódica está actualizando las estadísticas del anfitrión, está "
"intentando obtener el disco %(i_name)s, pero el disco ha sido removido por "
"operaciones concurrentes como la modificación de tamaño."

#: nova/virt/libvirt/driver.py:5140
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but access is denied. It is most likely due to a VM that exists "
"on the compute node but is not managed by Nova."
msgstr ""

#: nova/virt/libvirt/firewall.py:50
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work correctly."
msgstr ""
"El módulo lLibvirt no se ha podido cargar. NWFilterFirewall no funcionará "
"correctamente."

#: nova/virt/libvirt/imagecache.py:317
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""
"La instancia %(instance)s utiliza un archivo de respaldo %(backing)s que no "
"aparece en el servicio de la imagen"

#: nova/virt/libvirt/imagecache.py:494
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in use! "
"instances: %(instance_list)s"
msgstr ""
"%(id)s (%(base_file)s): aviso -- se está utilizando un archivo base ausente. "
"instancias: %(instance_list)s"

#: nova/virt/libvirt/imagecache.py:544
#, python-format
msgid "Unknown base file: %s"
msgstr "Archivo de base desconocido: %s "

#: nova/virt/libvirt/lvm.py:67
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. Virtual "
"volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""
"El grupo de volumen %(vg)s no podrá retener el volumen disperso %(lv)s. El "
"tamaño del volumen virtual es %(size)db, pero el espacio libre en el grupo "
"de volúmenes es solo %(free_space)db."

#: nova/virt/libvirt/rbd_utils.py:268
#, python-format
msgid "rbd remove %(volume)s in pool %(pool)s failed"
msgstr ""

#: nova/virt/libvirt/utils.py:69 nova/virt/libvirt/utils.py:75
msgid "systool is not installed"
msgstr "systool no está instalado"

#: nova/virt/libvirt/volume.py:132
#, python-format
msgid "Unknown content in connection_info/qos_specs: %s"
msgstr "Contenido desconocido en connection_info/qos_specs: %s"

#: nova/virt/libvirt/volume.py:297
#, python-format
msgid ""
"ISCSI volume not yet found at: %(disk_dev)s. Will rescan & retry.  Try "
"number: %(tries)s"
msgstr ""
"El volumen ISCSI aún no se ha encontrado en: %(disk_dev)s. Se volverá a "
"explorar y se reintentará. Número de intentos: %(tries)s"

#: nova/virt/libvirt/volume.py:364
#, python-format
msgid "Unable to delete volume device %s"
msgstr "Incapaz de eliminar el dispositivo de volumen %s"

#: nova/virt/libvirt/volume.py:375
#, python-format
msgid ""
"Failed to remove multipath device descriptor %(dev_mapper)s. Exception "
"message: %(msg)s"
msgstr ""
"Fallo al remover el descriptor del dispositivo multiruta %(dev_mapper)s. "
"Mensaje de excepción: %(msg)s"

#: nova/virt/libvirt/volume.py:697 nova/virt/libvirt/volume.py:846
#, python-format
msgid "%s is already mounted"
msgstr "%s ya está montado "

#: nova/virt/libvirt/volume.py:742
#, python-format
msgid "AoE volume not yet found at: %(aoedevpath)s. Try number: %(tries)s"
msgstr ""
"El volumen AoE aún no se ha encontrado en: %(aoedevpath)s. Número de "
"intentos: %(tries)s"

#: nova/virt/libvirt/volume.py:934
#, python-format
msgid ""
"Fibre volume not yet found at: %(mount_device)s. Will rescan & retry.  Try "
"number: %(tries)s"
msgstr ""
"El volumen de fibra aún no se ha encontrado en: %(mount_device)s. Se volverá "
"a explorar y se reintentará. Número de intentos: %(tries)s"

#: nova/virt/libvirt/volume.py:995
#, python-format
msgid "multipath-tools probably work improperly. devices to remove = %s."
msgstr ""

#: nova/virt/libvirt/volume.py:1040
msgid "Value required for 'scality_sofs_config'"
msgstr "Valor necesario para 'scality_sofs_config'"

#: nova/virt/libvirt/volume.py:1051
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr "No se puede acceder a 'scality_sofs_config': %s"

#: nova/virt/libvirt/volume.py:1057
msgid "Cannot execute /sbin/mount.sofs"
msgstr "No se puede ejecutar /sbin/mount.sofs"

#: nova/virt/libvirt/volume.py:1072
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr "No se puede montar Scality SOFS, compruebe syslog por si hay errores"

#: nova/virt/vmwareapi/driver.py:96
msgid ""
"The VMware ESX driver is now deprecated and has been removed in the Juno "
"release. The VC driver will remain and continue to be supported."
msgstr ""

#: nova/virt/vmwareapi/driver.py:157
#, python-format
msgid "The following clusters could not be found in the vCenter %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:202
msgid "Instance cannot be found in host, or in an unknownstate."
msgstr ""

#: nova/volume/cinder.py:249
msgid ""
"Cinder V1 API is deprecated as of the Juno release, and Nova is still "
"configured to use it. Enable the V2 API in Cinder and set "
"cinder_catalog_info in nova.conf to use it."
msgstr ""
